# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20171108_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='code',
        ),
        migrations.RemoveField(
            model_name='role',
            name='group',
        ),
        migrations.AddField(
            model_name='permission',
            name='code',
            field=models.CharField(default=1, max_length=32, verbose_name='编码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permission',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Group', verbose_name='权限组'),
        ),
    ]
