# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_menue'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='menue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rbac.Menue', verbose_name='菜单名称'),
            preserve_default=False,
        ),
    ]
